---

- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker
    user: ubuntu

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - githubixx.kubectl
    - andrewrothstein.kubernetes-helm

  tasks:
    - name: adding existing user '{{ user }}' to group docker
      user:
        name: '{{ user }}'
        groups: docker
        append: true
