---

- hosts: all
  become: yes

  vars:
    jenkins_plugins:
      - blueocean
      - git
      - github
      - configuration-as-code
    jenkins_plugins_install_dependencies: true
    jenkins_prefer_lts: true

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins

  tasks:
    - name: Deny anonymous read access
      lineinfile:
        path: /var/lib/jenkins/config.xml
        line: "<denyAnonymousReadAccess>true</denyAnonymousReadAccess>"
        regexp: "<denyAnonymousReadAccess>"
      become: true
      become_user: jenkins
      become_method: sudo
      notify: 'restart jenkins'
