---

- hosts: all
  become: yes

  vars:
    jenkins_plugins:
      - blueocean
      - git
      - github
      - configuration-as-code
    jenkins_plugins_install_dependencies: true
    jenkins_prefer_lts: true

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
