---

- hosts: all
  become: yes

  vars:
    jenkins_plugins:
      - blueocean
      - git
      - github
    jenkins_plugins_install_dependencies: true

  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
