---
- hosts: all
  become: true

  vars:
    packages_list:
      - htop
      - jq
      - libsensors5
      - mc
      - mc
      - rsync
      - tmux
      - zsh

  roles:

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
        update_cache: true
      with_items: "{{ packages_list }}"
