---

- hosts: all
  become: true

  vars:
    pip_install_packages:
      - name: docker
    user: ubuntu
    minikube_download_dir: /opt/minikube

  roles:
    - geerlingguy.pip
    - geerlingguy.docker
    - gantsign.minikube
    - githubixx.kubectl

  tasks:
    - name: adding existing user '{{ user }}' to group docker
      user:
        name: '{{ user }}'
        groups: docker
        append: true
